export interface IMovie {
  adult:boolean,
  backdrop_path:string,
  title:string,
  original_title:string,
  genre_ids:any,
  release_date:string,
  runtime:number,
  poster_path:string,
  vote_average:number,
  budget:number,
  revenue:number,
  overview:string,
  isFavorite:boolean,
}
